### ISSUE TITLE
feature: Icona Like d'assignatures amb color si subscribed a la pàgina principal

### ISSUE THREAD

**Issue by puigde** [data-students/apunts-dades-old#16]

**Comment by PauMatas** [comment]
Hola @ainaluis, he vist que tant l'icona del llibre com la del cor de la main page tenen mida variable. No me n'havia adonat però va ser error meu ja fer-ho així amb les icones de llibre. Pots encarregarte'n de fer-les de mida estàtica? Sincerament no se com es fa 🙃

**Comment by ainaluis** [comment]
Sí. Aquesta nit ho intento fer. Lo del cor encara no acaba de funcionar encara. Jo me n'ocupo.
