### ISSUE TITLE
out of code: registrar usuaris al servei d'auth

### ISSUE THREAD

**Issue by puigde** [data-students/apunts-dades-old#17]

**Comment by puigde** [comment]
@PauMatas tenim pensat fer-ho directament dins del servei pel que tinc entès no?

**Comment by puigde** [comment]
> @PauMatas tenim pensat fer-ho directament dins del servei pel que tinc entès no?

Extenent una mica en això: la meva idea actual és que posem els usuaris manualment al google auth i que on login failure redireccionem a request create account. És bastant més lent que fer-ho via codi però donat que estarà opensource i que volem tots i cadascun dels usuaris validats manualment (alumnes gced) diria que de moment té més sentit que aquestes coses es gestionin des del servei de auth.

**Comment by PauMatas** [comment]
Penso que te sentit el que dius però estàs assumint que podem donar-li una llista d'usuaris a Google Auth. Jo quan havíem parlat de llista d'usuaris pensava aplicar la a BD saps?

**Comment by puigde** [comment]
Sip estava assumint això com vam parlar ahir sembla que no és una opció. He vist el teu fix acord el que hem parlat per whats i em sembla que està nice. Podem tirar d'això + script validador pel moment. @PauMatas diries està done per tancar l'issue i pel pre-launch (que la gent es registri)? si vols ho comentem aquesta nit

**Comment by PauMatas** [comment]
Ho veig bé, tanca'l. Aquesta nit en parlem.

**Comment by puigde** [comment]
Back to the OG google forms #makestuff

**Comment by puigde** [comment]
[forms link](https://forms.gle/iCrARMLVu2hDcsrq9) i tanquem issue
