### ISSUE TITLE
Autenticació de correu upc per a poder fer una Account Request

### ISSUE THREAD

**Issue by PauMatas** [data-students/apunts-dades-old#18]
Validar que l'usuari és qui diu ser, és a dir que el correu que introdueix al form de Account Request és el seu i hi té accés sense perisitir un nou usuari a la BD.

**Comment by puigde** [comment]
context: pel launch hem fet servir [un forms](https://forms.gle/iCrARMLVu2hDcsrq9) per assegurar la auth dels usuaris però ens agradaria que això és pogués demanr des de la web en un futur.

**Comment by puigde** [comment]
tanquem perquè no hi ha account request
