### ISSUE TITLE
Treure mentides

### ISSUE THREAD

**Issue by PauMatas** [data-students/apunts-dades-old#21]
- [x] Esborrar el botó de preferències
- [x] Deixar de dir que rebràs notificacions quan segueixes una assignatura
- [x] #23
- [x] 'Penja apunts' a la pàgina principal al inici
- [x] Create account request fora

**Comment by PauMatas** [comment]
Canviar el color de la component i posar-la la primera de totes
![Captura de pantalla 2024-02-16 a les 23 54 00](https://github.com/data-students/apunts-dades/assets/61761147/f00d9f3b-468b-4868-a8cf-a22d79ebfd74)

**Comment by puigde** [comment]
* Treure botó de create account request
