### ISSUE TITLE
Sou uns matats però ídols a la vegada

### ISSUE THREAD

**Issue by Huguet57** [data-students/apunts-dades-old#24]
Next.js, Tailwind i Typescript. Aquí hay nivel.

**Comment by Huguet57** [comment]
Hi falta Rust

**Comment by Huguet57** [comment]
<img width="381" alt="Captura de pantalla 2024-02-17 a les 13 17 44" src="https://github.com/data-students/apunts-dades/assets/6130834/3f7ccd2c-0d06-4d8e-86d1-f7595fd6b193">

Ah, i sou uns cutres. Us el pago jo si cal

**Comment by PauMatas** [comment]
> <img width="381" alt="Captura de pantalla 2024-02-17 a les 13 17 44" src="https://github.com/data-students/apunts-dades/assets/6130834/3f7ccd2c-0d06-4d8e-86d1-f7595fd6b193">
> 
> 
> 
> Ah, i sou uns cutres. Us el pago jo si cal

apunts-dades.cat 😉

**Comment by Huguet57** [comment]
Ho considero com a tancat, doncs. Ja ho podeu canviar a la pàgina del GitHub.

**Comment by Huguet57** [comment]
Quan recuperi la meva compta estudiantat.upc.edu miro de què va que de moment no m'entero de res
