### ISSUE TITLE
migration: Migrate stuff out of planetscale

### ISSUE THREAD

**Issue by puigde** [data-students/apunts-dades-old#39]
Planetscale's hobby tier (which we were running on) is being deprecated [FAQS LINK](https://planetscale.com/docs/concepts/hobby-plan-deprecation-faq) the minimal 39$/month feels like an overkill for the amount of traffic we plan to hold in the upcoming future. If no cheaper minimal plan (for example: previous hobby for 5$) is offered in the upcoming week (I don't think they will) I think that we would need a migration. 

There are many other free alternatives on the cloud with super minimal setup but then we might re-encounter this same issue again in a year let's say.

One thing that I would love to learn is how to rent a cheap computer [at hetzner for example](https://www.hetzner.com/) and run our stuff there. It's still 30 bucks but not only for the DB, we can pretty much run everything AED related that we want. Our userbase is super centralized geographically and we don't run any critical data services we don't need an edge solution.

I don't know why I started writing this in English but here it goes.

**Comment by hooopo** [comment]
TiDB Serverless is free up to 5GB and 50M Request Units (RUs) without the need to enter a credit card. It is compatible with MySQL, so migrating from PlanetScale to TiDB Serverless should be very easy.
https://docs.pingcap.com/tidb/stable/dev-guide-sample-application-nextjs

**Comment by PauMatas** [comment]
> TiDB Serverless is free up to 5GB and 50M Request Units (RUs) without the need to enter a credit card. It is compatible with MySQL, so migrating from PlanetScale to TiDB Serverless should be very easy.
> https://docs.pingcap.com/tidb/stable/dev-guide-sample-application-nextjs

Thanks for your advice, the migration was unexpectedly fast and clean
