### ISSUE TITLE
feature: possibilitat de indicar l'any que has cursat l'assignatura

### ISSUE THREAD

**Issue by marcfranquesa** [data-students/apunts-dades-old#43]
He entrat al 2020 al grau, he cursat assignatures de 2n al 2023 (jaja) estaria bé deixar default 2021 (en el meu cas) però poder canviar-ho.

**Comment by puigde** [comment]
Potser afegir un selector de year al forms de submit com el que tenim a tipus.

![image](https://github.com/data-students/apunts-dades/assets/83642160/a3dad854-f84c-406b-84f0-2a3fc34a9638)

L'únic requisit que li posaria és que estigui per defecte a l'any que t'hauria tocat cursar l'assignatura seguint el path habitual.

Si t'animes assigna't i nari.

**Comment by marcfranquesa** [comment]
crec que no em puc assignar pero si si

**Comment by PauMatas** [comment]
Fet! Tot teu

**Comment by marcfranquesa** [comment]
![d01](https://github.com/data-students/apunts-dades/assets/110655741/23d69af2-6827-4d28-9b32-1fdb73e90cfa)
