### ISSUE TITLE
feature: searchbar

### ISSUE THREAD

**Issue by PauMatas** [data-students/apunts-dades-old#47]
Valdria la pena plantejar incloure una barra de cerca tant a la pàgina d'inici com a cada assignatura per tal de poder accedir més àgilment al contingut. Aquesta cerca hauria d'afectar tant al títol com al text dels posts (no al contingut dels PDF). Si la barra es fa servir des d'una assignatura caldria cercar només dins del contingut d'aquesta.

**Comment by puigde** [comment]
M'agrada molt aquesta!! Boníssima
