### ISSUE TITLE
bug: duplicated preguntes, comments i answers

### ISSUE THREAD

**Issue by puigde** [data-students/apunts-dades-old#68]
Bloquejar el submit mentre s'està penjant o si ja n'hi ha una amb els mateixos continguts.

**Comment by PauMatas** [comment]
Això pot ser que ho solventessim ja, @puigde ?
A prod quan ho intentes et tira un toast i no et deixa pujar apunts per el que vam veure amb en @marcfranquesa .

**Comment by puigde** [comment]
Diria que sí! ben vist, tanco issue i si tornes a passar el reobrim.
