### ISSUE TITLE
No es poden pujar apunts a "Altres"

### ISSUE THREAD

**Issue by claudiamur** [data-students/apunts-dades-old#78]
He intentat penjar apunts a "Altres" i em surt aquest error:

Request failed with status code 422

**Comment by PauMatas** [comment]
Bones @claudiamur, primer de tot mil gràcies per a reportar el problema. Hem detectat què era el que fallava i ho hem solucionat. Tanco la issue però si et seguissis trobant amb el mateix problema no dubtis en reobrir-la.
Per últim, qualsevol bug més que trobis estarem encantats en solucionar-lo.
