### ISSUE TITLE
No està funcionant submit a prod

### ISSUE THREAD

**Issue by marcfranquesa** [data-students/apunts-dades-old#81]
@PauMatas maybe algo de la teva PR (imagino que de multiples pdfs)

**Comment by marcfranquesa** [comment]
update: penjant només un pdf dona error, penjant 2 no diu res

**Comment by PauMatas** [comment]
@marcfranquesa No sóc capaç de reproduïr els error ni en dev ni en prod, dona'm llum

btw: he explicat millor el tema del mail i arreglat un bug de frontend quan afegies fitxers al form amb pantalles petites

**Comment by marcfranquesa** [comment]
Ens hem connectat amb en @PauMatas i el problema és al penjar fitxers grans
