### ISSUE TITLE
Mobile responsiveness

### ISSUE THREAD

**Issue by PauMatas** [data-students/apunts-dades-old#83]
Estaria bé revisar tota la web en format mòbil. No es l'objectiu inicial de la web però segur que molta gent hi entrarà via dispositiu petit. Aixi evitem coses com:
![image](https://github.com/data-students/apunts-dades/assets/61761147/fc6465c1-7b34-433e-978c-65b8d6c3580a)

**Comment by puigde** [comment]
Politely disagree :):)

**Comment by puigde** [comment]
Crec que la feina que porta no compensa les dues vegades l'any que algú hi entrarà amb el mòbil.

**Comment by puigde** [comment]
MMMMMMMMM bueno potser no és tanta feina, els components haurien de ser reactius pel mòbil, son només casos on el text és massa gran? Llavors potser podríem captar el dispositiu de l'usuari i posar un ternary ? : on tinguem textos d'aquests llarguets.

**Comment by PauMatas** [comment]
Exacte, en principi son tonterietes que pensava fer algun dia for fun, però estic d'acord que és 0 prio stuff
